### ISSUE TITLE
When using SOEM to control ELMO Gold series Drive, the elmo will switch to switch-on-disabled state sometimes

### ISSUE THREAD

**Issue by crown133** [leggedrobotics/elmo_ethercat_sdk#11]
Background: I'm trying to use this pakage to control the elmo gold twitter.

Issues: When using SOEM to control elmo drive, the elmo can be initialized to operation-enabled state successfully and worked well, but it will switch to switch-on-disabled state sometimes aspecially when there are other threads running simultaneously.

I want to know why the elmo switched from operation-enabled state to switch-on-disabled state automatically even I didn't change the 'controword'. And also why the thread priority or other reasons will cause this problem?

I'll be appreciate it if you can give me some advice.

**Comment by HDH666** [comment]
How did you solve this issue? I'm encountering the same problem.
I'm using the ament_cmake branch.

**Comment by crown133** [comment]
> How did you solve this issue? I'm encountering the same problem. I'm using the ament_cmake branch.
 I have replaced the original computer with a customed industrial pc, patched a linux RT kernel and changed some settings in bios. Everything worked reliably in new system while the cycle time was set to be 1ms.
