### ISSUE TITLE
New elmo_examples ?

### ISSUE THREAD

**Issue by Linshiyuan** [leggedrobotics/elmo_ethercat_sdk#6]
Hi, 
I found elmo_examples in some old commits, is there new elmo_examples here? It would be helpful to have some examples.
Thanks.

**Comment by JohannesPankert** [comment]
We have moved the example to the device_configurator repo:
https://github.com/leggedrobotics/ethercat_device_configurator/blob/master/src/standalone.cpp
You can check whether that works for you. We should probably add a link to this repo into the readme.
